service: foodapi

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  environment:
    mainTableName: ${self:custom.mainTableName}
    categoryTableName: ${self:custom.categoryTableName}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:*
      Resource: '*'

functions:
  addFood:
    handler: lambdas/endpoints/addFood.handler
    events:
      - http:
          path: addFood/
          method: POST
          cors: true
  getFood:
    handler: lambdas/endpoints/getFood.handler
    events:
      - http:
          path: getFood/{ID}
          method: GET
          cors: true
  addCategory:
    handler: lambdas/endpoints/addCategory.handler
    events:
      - http:
          path: addCategory/
          method: POST
          cors: true

custom:
  mainTableName: food-items
  categoryTableName: food-categories

resources:
  Resources:
    FoodItems:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.mainTableName}
        AttributeDefinitions:
          - AttributeName: ID
            AttributeType: S
        KeySchema:
          - AttributeName: ID
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
    FoodCategories:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.categoryTableName}
        AttributeDefinitions:
          - AttributeName: ID
            AttributeType: S
        KeySchema:
          - AttributeName: ID
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
