service: foodapi

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  environment:
    mainTableName: ${self:custom.mainTableName}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:*
      Resource: '*'

functions:
  addFood:
    handler: lambdas/endpoints/addFood.handler
    events:
      - http:
        path: addFood
        method: POST
        cors: true

custom:
  mainTableName: food-items

resources:
  Resources:
    FoodItems:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.mainTableName}
        AttributeDefinitions:
          - AttributeName: ID
            AttributeType: S
        KeySchema:
          - AttributeName: ID
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
