service: foodapi

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  environment:
    ingredientsTableName: ${self:custom.ingredientsTableName}
    recipeTableName: ${self:custom.recipeTableName}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:*
      Resource: '*'

functions:
  addIngredients:
    handler: lambdas/endpoints/addIngredients.handler
    events:
      - http:
          path: addIngredients/
          method: POST
          cors: true
  getIngredients:
    handler: lambdas/endpoints/getIngredients.handler
    events:
      - http:
          path: getIngredients/
          method: POST
          cors: true
  addRecipes:
    handler: lambdas/endpoints/addRecipes.handler
    events:
      - http:
          path: addRecipes/
          method: POST
          cors: true

custom:
  ingredientsTableName: ingredients
  recipeTableName: recipes

resources:
  Resources:
    Ingredients:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.ingredientsTableName}
        AttributeDefinitions:
          - AttributeName: ID
            AttributeType: S
        KeySchema:
          - AttributeName: ID
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
    Recipes:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.recipeTableName}
        AttributeDefinitions:
          - AttributeName: ID
            AttributeType: S
        KeySchema:
          - AttributeName: ID
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
